### ISSUE TITLE
crash on website open

### ISSUE THREAD

**Issue by Kisakay** [real2two/dashactyl#11]
When i would like to go on my website the site crashing with this error:

express-session deprecated undefined resave option; provide resave option index.js:73:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:73:9
[WEBSITE] The dashboard has successfully loaded on port 81.
(node:10626) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'enabled' of undefined
    at eval (eval at app.all (/root/dashactyl-0.3.6/api/pages.js:73:13), <anonymous>:15:43)
    at eval (eval at app.all (/root/dashactyl-0.3.6/api/pages.js:73:13), <anonymous>:21:5)
    at app.all (/root/dashactyl-0.3.6/api/pages.js:73:13)
    at Layer.handle [as handle_request] (/root/dashactyl-0.3.6/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:137:13)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:131:14)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:131:14)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:131:14)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:131:14)
    at next (/root/dashactyl-0.3.6/node_modules/express/lib/router/route.js:131:14)
(node:10626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by real2two** [comment]
This error could only occur if you messed up settings.json. (and don't leak your settings.json here)
I'd use https://jsonlint.com/ to check your settings.json.
