### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ghost** [real2two/dashactyl#31]
TypeError: apifile.load is not a function
    at /home/runner/dashactyl-3/index.js:205:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/dashactyl-3/index.js:203:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/dashactyl-3/api/arcio.js:2:17)Hint: hit control+c anytime to enter REPL.

**Comment by real2two** [comment]
Not specific.
